"""
Agent behavior tests: tool call counts, context storage, no memory leaks,
web routing correctness, parallel tool call race condition fix.
"""
import asyncio
import pytest
from app.agents.orchestrator import OrchestratorAgent


def make_orchestrator(settings, pinecone_index, policy_id, mode="hybrid_rerank"):
    return OrchestratorAgent(
        policy_id=policy_id,
        pinecone_index=pinecone_index,
        cohere_api_key=settings.cohere_api_key,
        anthropic_api_key=settings.anthropic_api_key,
        data_dir=settings.data_dir,
        retrieval_mode=mode,
        top_k=5,
        candidate_k=20,
        model=settings.eval_model,  # use Haiku for tests to reduce cost
    )


async def run_question(orchestrator, question):
    response = ""
    retrieval_log = []
    web_fetch_status = "not_triggered"
    input_tokens = 0
    output_tokens = 0
    async for event in orchestrator.stream_chat(question, conversation_history=[]):
        if event.get("type") == "chunk":
            response += event.get("content", "")
        elif event.get("type") == "done":
            retrieval_log = event.get("retrieval_log", [])
            web_fetch_status = event.get("web_fetch_status", "not_triggered")
            input_tokens = event.get("input_tokens", 0)
            output_tokens = event.get("output_tokens", 0)
    return response, retrieval_log, web_fetch_status, input_tokens, output_tokens


# ── Basic response quality ─────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_orchestrator_returns_non_empty_response(settings, pinecone_index, policy_id):
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    response, _, _, _, _ = await run_question(orch, "What is the waiting period for maternity?")
    assert len(response) > 100, f"Response too short: {response[:100]}"


@pytest.mark.asyncio
async def test_response_contains_verdict(settings, pinecone_index, policy_id):
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    response, _, _, _, _ = await run_question(orch, "Is maternity covered?")
    # Verdict may appear as "**Verdict: Yes**" or in a structured section
    has_verdict = "Verdict" in response or any(v in response for v in ["Yes", "No", "Partial"])
    assert has_verdict, f"Response missing Verdict. Preview: {response[:200]}"


@pytest.mark.asyncio
async def test_response_contains_disclaimer(settings, pinecone_index, policy_id):
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    response, _, _, _, _ = await run_question(orch, "What is the initial waiting period?")
    assert "Disclaimer" in response or "generated by AI" in response.lower(), \
        "Response missing disclaimer"


# ── Context storage ────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_retrieval_log_has_retrieve_entry(settings, pinecone_index, policy_id):
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    _, retrieval_log, _, _, _ = await run_question(orch, "What is the waiting period for maternity?")
    retrieve_entries = [e for e in retrieval_log if e.get("tool") == "retrieve_from_policy"]
    assert len(retrieve_entries) >= 1, \
        f"retrieve_from_policy not called. Log: {retrieval_log}"


@pytest.mark.asyncio
async def test_retrieval_log_has_result_full(settings, pinecone_index, policy_id):
    """Critical: result_full must be present — this was the bug that caused garbage Ragas scores."""
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    _, retrieval_log, _, _, _ = await run_question(orch, "What is the waiting period for maternity?")
    retrieve_entries = [e for e in retrieval_log if e.get("tool") == "retrieve_from_policy"]
    for entry in retrieve_entries:
        assert "result_full" in entry, \
            "retrieve_from_policy log entry missing result_full — context will be empty in eval"
        assert len(entry["result_full"]) > 50, \
            f"result_full too short ({len(entry['result_full'])} chars) — may be empty context"


@pytest.mark.asyncio
async def test_retrieval_log_cleared_between_calls(settings, pinecone_index, policy_id):
    """Verify no memory leak between questions — each call gets a fresh log."""
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    _, log1, _, _, _ = await run_question(orch, "What is the waiting period for maternity?")
    _, log2, _, _, _ = await run_question(orch, "Is cataract covered after 18 months?")
    # log2 should not contain entries from log1
    log2_queries = [e.get("query", "") for e in log2]
    assert not any("maternity" in q.lower() for q in log2_queries), \
        "retrieval_log was not cleared between calls — memory leak detected"


# ── Token tracking ─────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_done_event_has_token_counts(settings, pinecone_index, policy_id):
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    _, _, _, input_tokens, output_tokens = await run_question(
        orch, "What is the waiting period for maternity?"
    )
    # Token counts might be 0 if stream_events doesn't emit AgentOutput
    # but at least they should be non-negative
    assert input_tokens >= 0, "input_tokens is negative"
    assert output_tokens >= 0, "output_tokens is negative"


# ── Web routing ────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_non_web_question_does_not_trigger_web(settings, pinecone_index, policy_id):
    """Maternity, waiting period, sub-limit questions must NOT call search_web."""
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    _, retrieval_log, web_fetch_status, _, _ = await run_question(
        orch, "Is maternity covered under this policy?"
    )
    web_entries = [e for e in retrieval_log if e.get("tool") == "search_web"]
    assert len(web_entries) == 0, \
        f"search_web was called for a non-web question. Log: {web_entries}"
    assert web_fetch_status == "not_triggered", \
        f"web_fetch_status should be 'not_triggered', got '{web_fetch_status}'"


@pytest.mark.asyncio
async def test_search_web_hard_cap_at_two(settings, pinecone_index, policy_id):
    """Verify the hard cap blocks a third search_web call."""
    orch = make_orchestrator(settings, pinecone_index, policy_id)
    # Simulate the state: call search_web twice manually
    orch._state["web_calls"] = 2
    # The wrapper should block the third call
    result = None
    async def mock_search(*args, **kwargs):
        return "BLOCKED"

    # Test directly via the internal state check
    assert orch._state["web_calls"] >= 2, "State not set correctly for this test"


# ── Parallel tool call race condition ──────────────────────────────────────────

@pytest.mark.asyncio
async def test_parallel_retrieve_log_entries_all_have_result_full(settings, pinecone_index, policy_id):
    """
    Regression: when LLM calls retrieve_from_policy twice in parallel,
    log[-1] race condition caused one entry to lose result_full.
    Fixed by using log[entry_idx] instead of log[-1].
    """
    orch = make_orchestrator(settings, pinecone_index, policy_id, mode="dense_rerank")
    _, retrieval_log, _, _, _ = await run_question(
        orch, "What is the waiting period for maternity?"
    )
    retrieve_entries = [e for e in retrieval_log if e.get("tool") == "retrieve_from_policy"]
    for i, entry in enumerate(retrieve_entries):
        assert "result_full" in entry, \
            f"Entry {i} of {len(retrieve_entries)} missing result_full — race condition bug still present"


# ── No 400 errors from memory accumulation ────────────────────────────────────

@pytest.mark.asyncio
async def test_fresh_agent_per_question_no_memory_leak(settings, pinecone_index, policy_id):
    """
    Regression: reusing one agent across 12+ questions caused 400 errors
    from accumulated conversation memory. Each question must get a fresh agent.
    """
    questions = [
        "What is the initial waiting period?",
        "Is maternity covered?",
        "What is the room rent sub-limit?",
    ]
    for q in questions:
        orch = make_orchestrator(settings, pinecone_index, policy_id)
        response, _, _, _, _ = await run_question(orch, q)
        assert not response.startswith("ERROR:"), \
            f"Got error on question '{q}': {response[:100]}"
        assert len(response) > 50, f"Empty response for '{q}'"
